# This file is auto-generated by the wizig release workflow.
class Wizig < Formula
  desc "Mobile framework: native iOS/Android hosts with shared Zig runtime"
  homepage "https://wizig.org"
  version "0.0.4-dev"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/wizig-org/wizig/releases/download/v0.0.4-dev/wizig-0.0.4-dev-macos-arm64.tar.gz"
      sha256 "b20fd8ccf584d0f80357d48ee10f0661dae7ddec1e9c10b532e85c68b19def73"
    else
      url "https://github.com/wizig-org/wizig/releases/download/v0.0.4-dev/wizig-0.0.4-dev-macos-x86_64.tar.gz"
      sha256 "7bad2f78df6938d319a3186dccee0c2e269722bf326d7a0311585b43651c0d84"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/wizig-org/wizig/releases/download/v0.0.4-dev/wizig-0.0.4-dev-linux-arm64.tar.gz"
      sha256 "224bc2ead61bea2de47adde4866612fdf93b1554cf25ff6f9fbbd08e4ec352b3"
    else
      url "https://github.com/wizig-org/wizig/releases/download/v0.0.4-dev/wizig-0.0.4-dev-linux-x86_64.tar.gz"
      sha256 "424581e8d9f7920dbf3b04a0723efdc39217243aa3cb436919850ca3c1e2eb87"
    end
  end

  def install
    bin.install "bin/wizig"
    (share/"wizig").install Dir["share/wizig/*"]
    (lib).install Dir["lib/*"] if Dir.exist?("lib")
    (include).install Dir["include/*"] if Dir.exist?("include")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wizig version")
  end
end
