# This file is auto-generated by the wizig release workflow.
class WizigAT007 < Formula
  desc "Mobile framework: native iOS/Android hosts with shared Zig runtime"
  homepage "https://wizig.org"
  version "0.0.7"
  license "MIT"

  keg_only :versioned_formula

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/wizig-org/wizig/releases/download/0.0.7/wizig-0.0.7-macos-arm64.tar.gz"
      sha256 "de652ebb0a0227d65d9cd28beb553086f2240a5f9278b649a6514e05cec34055"
    else
      url "https://github.com/wizig-org/wizig/releases/download/0.0.7/wizig-0.0.7-macos-x86_64.tar.gz"
      sha256 "96bc98ab3a15fcef21fc851afe38274f51de6fda8ca96b174d9a9c0c7cf41e0f"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/wizig-org/wizig/releases/download/0.0.7/wizig-0.0.7-linux-arm64.tar.gz"
      sha256 "3e5ebba184f99866de8b58033157cc320ca24bb1267bd91409991a7ad5da3c13"
    else
      url "https://github.com/wizig-org/wizig/releases/download/0.0.7/wizig-0.0.7-linux-x86_64.tar.gz"
      sha256 "28955f15d7420981ad5cded5b51f895322c054c4aacb4388b62d06485c88c3d7"
    end
  end

  def install
    bin.install "bin/wizig"
    (share/"wizig").install Dir["share/wizig/*"]
    (lib).install Dir["lib/*"] if Dir.exist?("lib")
    (include).install Dir["include/*"] if Dir.exist?("include")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wizig version")
  end
end
