# This file is auto-generated by the wizig release workflow.
class WizigAT0011 < Formula
  desc "Mobile framework: native iOS/Android hosts with shared Zig runtime"
  homepage "https://wizig.org"
  version "0.0.11"
  license "MIT"

  keg_only :versioned_formula

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/wizig-org/wizig/releases/download/0.0.11/wizig-0.0.11-macos-arm64.tar.gz"
      sha256 "9fa3c78ef4a12b786263e638de7f8cd83fbc9ab5ed15c3ac18f07eee3215c990"
    else
      url "https://github.com/wizig-org/wizig/releases/download/0.0.11/wizig-0.0.11-macos-x86_64.tar.gz"
      sha256 "e30c46a2861675ea922c238fb398f41e4fa453b55013fcb5d54db0aae3ed0ede"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/wizig-org/wizig/releases/download/0.0.11/wizig-0.0.11-linux-arm64.tar.gz"
      sha256 "c1a7073e819df3b716477132aa746958e08ab81ca1ab55c2d82d18bfb965a48b"
    else
      url "https://github.com/wizig-org/wizig/releases/download/0.0.11/wizig-0.0.11-linux-x86_64.tar.gz"
      sha256 "762ae5fde444da8325d64b50ff263f9bea08cb8f65d356e8b6e4b40a4670040e"
    end
  end

  def install
    bin.install "bin/wizig"
    (share/"wizig").install Dir["share/wizig/*"]
    (lib).install Dir["lib/*"] if Dir.exist?("lib")
    (include).install Dir["include/*"] if Dir.exist?("include")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wizig version")
  end
end
