# This file is auto-generated by the wizig release workflow.
class WizigAT0012 < Formula
  desc "Mobile framework: native iOS/Android hosts with shared Zig runtime"
  homepage "https://wizig.org"
  version "0.0.12"
  license "MIT"

  keg_only :versioned_formula

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/wizig-org/wizig/releases/download/0.0.12/wizig-0.0.12-macos-arm64.tar.gz"
      sha256 "e621cc408de93806a60ecbad1fb3fa58cc4f6b5a51242999953d78faefc40972"
    else
      url "https://github.com/wizig-org/wizig/releases/download/0.0.12/wizig-0.0.12-macos-x86_64.tar.gz"
      sha256 "c2de00e8c16230c5b3a3b4ebea157c6197226f794192e5d9a85c056d5c8562e8"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/wizig-org/wizig/releases/download/0.0.12/wizig-0.0.12-linux-arm64.tar.gz"
      sha256 "1f59f23b063e76298206adf9d35f73a894c0de6712408ac33577064747ea1198"
    else
      url "https://github.com/wizig-org/wizig/releases/download/0.0.12/wizig-0.0.12-linux-x86_64.tar.gz"
      sha256 "10a15aee08d1c42eb30c2d8a9cb473e9c40d602cf2c32a08271661de2cdd5471"
    end
  end

  def install
    bin.install "bin/wizig"
    (share/"wizig").install Dir["share/wizig/*"]
    (lib).install Dir["lib/*"] if Dir.exist?("lib")
    (include).install Dir["include/*"] if Dir.exist?("include")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wizig version")
  end
end
