# This file is auto-generated by the wizig release workflow.
class WizigAT004 < Formula
  desc "Mobile framework: native iOS/Android hosts with shared Zig runtime"
  homepage "https://wizig.org"
  version "0.0.4"
  license "MIT"

  keg_only :versioned_formula

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/wizig-org/wizig/releases/download/0.0.4/wizig-0.0.4-macos-arm64.tar.gz"
      sha256 "96ba6e5204535d200949fedc6c608220a3d3255550a1b4937c75d5093db736d7"
    else
      url "https://github.com/wizig-org/wizig/releases/download/0.0.4/wizig-0.0.4-macos-x86_64.tar.gz"
      sha256 "4d9d4aa4057f1a58c63439310fefae3c591184dcd439516f86fc592afe08f0d4"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/wizig-org/wizig/releases/download/0.0.4/wizig-0.0.4-linux-arm64.tar.gz"
      sha256 "6a4dd1b9184c19ad419921a5c5d876a184b0e99fc086751b1d6b5a702dff62f4"
    else
      url "https://github.com/wizig-org/wizig/releases/download/0.0.4/wizig-0.0.4-linux-x86_64.tar.gz"
      sha256 "190b6736d0739909ec767491c37b4d16a0f65834284b7c731fc6d7f28ebbba09"
    end
  end

  def install
    bin.install "bin/wizig"
    (share/"wizig").install Dir["share/wizig/*"]
    (lib).install Dir["lib/*"] if Dir.exist?("lib")
    (include).install Dir["include/*"] if Dir.exist?("include")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wizig version")
  end
end
