# This file is auto-generated by the wizig release workflow.
class WizigAT003 < Formula
  desc "Mobile framework: native iOS/Android hosts with shared Zig runtime"
  homepage "https://wizig.org"
  version "0.0.3"
  license "MIT"

  keg_only :versioned_formula

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/wizig-org/wizig/releases/download/0.0.3/wizig-0.0.3-macos-arm64.tar.gz"
      sha256 "57f3a1803319f8b1122cba3d39d9c302636607e72253b974c8ec38080ea83a5f"
    else
      url "https://github.com/wizig-org/wizig/releases/download/0.0.3/wizig-0.0.3-macos-x86_64.tar.gz"
      sha256 "467b601d0c8918df365d98b9dc9d9702914ca1be5419db0159ff7532a9b9ebb7"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/wizig-org/wizig/releases/download/0.0.3/wizig-0.0.3-linux-arm64.tar.gz"
      sha256 "485ac2006f4d2c3deef68e59b08a30a467bd9dcac751b2e2d41a4d9ec8c3f502"
    else
      url "https://github.com/wizig-org/wizig/releases/download/0.0.3/wizig-0.0.3-linux-x86_64.tar.gz"
      sha256 "b993557169ae6f3833a503b2275db98a6790151921a5f4e549d0169312deb2c5"
    end
  end

  def install
    bin.install "bin/wizig"
    (share/"wizig").install Dir["share/wizig/*"]
    (lib).install Dir["lib/*"] if Dir.exist?("lib")
    (include).install Dir["include/*"] if Dir.exist?("include")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wizig version")
  end
end
