# This file is auto-generated by the wizig release workflow.
class WizigAT008 < Formula
  desc "Mobile framework: native iOS/Android hosts with shared Zig runtime"
  homepage "https://wizig.org"
  version "0.0.8"
  license "MIT"

  keg_only :versioned_formula

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/wizig-org/wizig/releases/download/0.0.8/wizig-0.0.8-macos-arm64.tar.gz"
      sha256 "891c6052b5c2052d2013f0f80a4ef3b5eb0e65525617293363586e3737394a0d"
    else
      url "https://github.com/wizig-org/wizig/releases/download/0.0.8/wizig-0.0.8-macos-x86_64.tar.gz"
      sha256 "68b101dca50d0b9175b181ea795ec6715c73879ebeebbb4d36d35f59720a1644"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/wizig-org/wizig/releases/download/0.0.8/wizig-0.0.8-linux-arm64.tar.gz"
      sha256 "3a5805ac8146c07fab8e0e3c0a90211bae358c87e267eca692ffc4a87594643c"
    else
      url "https://github.com/wizig-org/wizig/releases/download/0.0.8/wizig-0.0.8-linux-x86_64.tar.gz"
      sha256 "558e85179f6fa150a79778f44c4095c2bf69ade26c5db2e57061ab4b25e9142f"
    end
  end

  def install
    bin.install "bin/wizig"
    (share/"wizig").install Dir["share/wizig/*"]
    (lib).install Dir["lib/*"] if Dir.exist?("lib")
    (include).install Dir["include/*"] if Dir.exist?("include")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wizig version")
  end
end
