# This file is auto-generated by the wizig release workflow.
class WizigAT009 < Formula
  desc "Mobile framework: native iOS/Android hosts with shared Zig runtime"
  homepage "https://wizig.org"
  version "0.0.9"
  license "MIT"

  keg_only :versioned_formula

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/wizig-org/wizig/releases/download/0.0.9/wizig-0.0.9-macos-arm64.tar.gz"
      sha256 "a411bbd322aed2d24ba353eb97f6610050a297bad6fda0c24eae5d64d29e772a"
    else
      url "https://github.com/wizig-org/wizig/releases/download/0.0.9/wizig-0.0.9-macos-x86_64.tar.gz"
      sha256 "ddbc34f626da96c9dd5a690a0a253cb6d7cd74d381c91174af3ae85d4d6bc652"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/wizig-org/wizig/releases/download/0.0.9/wizig-0.0.9-linux-arm64.tar.gz"
      sha256 "ddb9acb95f5aaa4df65738de6e55a08843a9a4e3d2f386221a341e287d82958f"
    else
      url "https://github.com/wizig-org/wizig/releases/download/0.0.9/wizig-0.0.9-linux-x86_64.tar.gz"
      sha256 "9cc90b8fd78cdb97f70c3264144f12123cd8b9a65ce775540a6f6db10ae92121"
    end
  end

  def install
    bin.install "bin/wizig"
    (share/"wizig").install Dir["share/wizig/*"]
    (lib).install Dir["lib/*"] if Dir.exist?("lib")
    (include).install Dir["include/*"] if Dir.exist?("include")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wizig version")
  end
end
