# This file is auto-generated by the wizig release workflow.
class WizigAT006 < Formula
  desc "Mobile framework: native iOS/Android hosts with shared Zig runtime"
  homepage "https://wizig.org"
  version "0.0.6"
  license "MIT"

  keg_only :versioned_formula

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/wizig-org/wizig/releases/download/0.0.6/wizig-0.0.6-macos-arm64.tar.gz"
      sha256 "0d88159af27b7c3e0c57db62e0fcdd0b8e2b596812df7ff931170d8c8a8345d6"
    else
      url "https://github.com/wizig-org/wizig/releases/download/0.0.6/wizig-0.0.6-macos-x86_64.tar.gz"
      sha256 "1e43fc174680a66546a64a59408eff84353c26d3173db3bd06fd1cf1c71c2970"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/wizig-org/wizig/releases/download/0.0.6/wizig-0.0.6-linux-arm64.tar.gz"
      sha256 "2f8c73246a7c9bb4c671a09ad7d710def0436d584d4755bbea6af1990008f0d5"
    else
      url "https://github.com/wizig-org/wizig/releases/download/0.0.6/wizig-0.0.6-linux-x86_64.tar.gz"
      sha256 "64413f3c66121fe76924dee0d4395520cf7ffe95a3df5df5042588d0f4b4b7aa"
    end
  end

  def install
    bin.install "bin/wizig"
    (share/"wizig").install Dir["share/wizig/*"]
    (lib).install Dir["lib/*"] if Dir.exist?("lib")
    (include).install Dir["include/*"] if Dir.exist?("include")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wizig version")
  end
end
