# This file is auto-generated by the wizig release workflow.
class WizigAT005 < Formula
  desc "Mobile framework: native iOS/Android hosts with shared Zig runtime"
  homepage "https://wizig.org"
  version "0.0.5"
  license "MIT"

  keg_only :versioned_formula

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/wizig-org/wizig/releases/download/0.0.5/wizig-0.0.5-macos-arm64.tar.gz"
      sha256 "3d949d2387329308c9b261d30b90e2b79ef6923f87a42f8a5952112040cc01b5"
    else
      url "https://github.com/wizig-org/wizig/releases/download/0.0.5/wizig-0.0.5-macos-x86_64.tar.gz"
      sha256 "4fae9e86e121416aef3f5016bd7eaae71a2558d69b37ee497d3beec807732ead"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/wizig-org/wizig/releases/download/0.0.5/wizig-0.0.5-linux-arm64.tar.gz"
      sha256 "f5b16170deafb7c8d9b164760b8a139d1570f95c07cfdee6ce1269743e04bad0"
    else
      url "https://github.com/wizig-org/wizig/releases/download/0.0.5/wizig-0.0.5-linux-x86_64.tar.gz"
      sha256 "5713ac86bb3926c4f6a33e286787999f43ecc9a998baba645916a4f2d285889b"
    end
  end

  def install
    bin.install "bin/wizig"
    (share/"wizig").install Dir["share/wizig/*"]
    (lib).install Dir["lib/*"] if Dir.exist?("lib")
    (include).install Dir["include/*"] if Dir.exist?("include")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wizig version")
  end
end
