# This file is auto-generated by the wizig release workflow.
class WizigAT0010 < Formula
  desc "Mobile framework: native iOS/Android hosts with shared Zig runtime"
  homepage "https://wizig.org"
  version "0.0.10"
  license "MIT"

  keg_only :versioned_formula

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/wizig-org/wizig/releases/download/0.0.10/wizig-0.0.10-macos-arm64.tar.gz"
      sha256 "89972a5fe11e27ac52406cc976b956ff77d79c807d542c5f347ead45a102226d"
    else
      url "https://github.com/wizig-org/wizig/releases/download/0.0.10/wizig-0.0.10-macos-x86_64.tar.gz"
      sha256 "625a23773b09380d28f86810674b6126c1e6b193e42429588e12b8b733af524a"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/wizig-org/wizig/releases/download/0.0.10/wizig-0.0.10-linux-arm64.tar.gz"
      sha256 "ccafe5023d5a11c745e7f29dcea0c6ac23dfe84b3b82889f72f53d6a792ad95f"
    else
      url "https://github.com/wizig-org/wizig/releases/download/0.0.10/wizig-0.0.10-linux-x86_64.tar.gz"
      sha256 "0a3a579138a52ac7657a2a18526a1793b4a5b1b81ebdf89bec8ca6b0d0422bad"
    end
  end

  def install
    bin.install "bin/wizig"
    (share/"wizig").install Dir["share/wizig/*"]
    (lib).install Dir["lib/*"] if Dir.exist?("lib")
    (include).install Dir["include/*"] if Dir.exist?("include")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wizig version")
  end
end
