# This file is auto-generated by the wizig release workflow.
class Wizig < Formula
  desc "Mobile framework: native iOS/Android hosts with shared Zig runtime"
  homepage "https://wizig.org"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/wizig-org/wizig/releases/download/v0.0.2/wizig-0.0.2-macos-arm64.tar.gz"
      sha256 "513618958e1db192422d76cec19ae65fbd2432f5e6fa6d4123eedd979240677a"
    else
      url "https://github.com/wizig-org/wizig/releases/download/v0.0.2/wizig-0.0.2-macos-x86_64.tar.gz"
      sha256 "35e717c576fbf33be3a159de2aa4c013b4f2edcc0c05a069051271670f65fd09"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/wizig-org/wizig/releases/download/v0.0.2/wizig-0.0.2-linux-arm64.tar.gz"
      sha256 "53c2f4d9fb2d4f92f71607d6837f13cfad477cc532f522bd618fb038ffc3a751"
    else
      url "https://github.com/wizig-org/wizig/releases/download/v0.0.2/wizig-0.0.2-linux-x86_64.tar.gz"
      sha256 "5f5f95708003ac1bffe41cf24f76a37b41f02a319d2da0f597c225d87aae28c1"
    end
  end

  def install
    bin.install "bin/wizig"
    (share/"wizig").install Dir["share/wizig/*"]
    (lib).install Dir["lib/*"] if Dir.exist?("lib")
    (include).install Dir["include/*"] if Dir.exist?("include")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wizig version")
  end
end
